mixed-port: 7890 # http(s) and SOCKS5
redir-port: 7892 # Redirect TCP and TProxy UDP

ipv6: true # 监听 ipv6，如果你网络不支持 ipv6 就别开

mode: rule # rule/global/direct/script

geodata-mode: true
geo-update-interval: 72 #每 72 小时更新一次 geo 文件

log-level: info

allow-lan: true # 允许局域网其他机器使用代理
bind-address: "*" # 配合上面字段，允许全部局域网机器 ip

external-controller: 0.0.0.0:9090 # webui 监听 IP 端口
# external-ui: ui # webui 相对目录

profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: mixed # system(系统模式) or gvisor(google 的一种沙盒模式) or mixed(混合堆栈,tcp使用 `system`栈,udp使用 `gvisor`栈,使用体验可能相对更好)
  dns-hijack: # dns 劫持
    - any:53
  auto-route: true # 全局路由
  auto-redir: true # Linux nftable REDIRECT
  auto-detect-interface: true # 自动选择出口网卡

dns:
  enable: true # 启用 dns 处理
  prefer-h3: true # 启用 DOH http/3
  ipv6: true # 使用 ipv6 dns 解析，如果你网络不支持 ipv6 就别开
  nameserver:
    - 180.76.76.76
    - 114.114.114.114
  proxy-server-nameserver:
    - tls://8.8.4.4:853
    - tls://1.0.0.1:853

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - AUTO
      - Sall
    url: "https://www.google.com/generate_204"
    interval: 300

  - name: "AUTO"
    type: url-test
    use:
      - chromego
    url: "https://www.google.com/generate_204"
    interval: 300

  - name: "Sall"
    type: select
    use:
      - chromego
      - ripaojiedian
      - anaer
    url: "https://www.google.com/generate_204"
    interval: 300

proxy-providers:
  # sub:
  #   type: http
  #   path: ./proxy/sub.yaml
  #   url: "https://renzheapi.com/sub?target=clash&new_name=true&url=https%3A%2F%2Fpastebin.com%2Fraw%2FGxR5pELe&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini"
  #   interval: 1800
  #   health-check:
  #     enable: true
  #     url: "https://www.google.com/generate_204"
  #     interval: 300

  anaer:
    type: http
    path: ./proxy/anaer.yaml
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml"
    interval: 1800
    # health-check:
    #   enable: true
    #   url: "https://www.google.com/generate_204"
    #   interval: 300

  ripaojiedian:
    type: http
    path: ./proxy/ripaojiedian.yaml
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash"
    interval: 1800
    # health-check:
    #   enable: true
    #   url: "https://www.google.com/generate_204"
    #   interval: 300

  # ssrsub:
  #   type: http
  #   path: ./proxy/ssrsub.yaml
  #   url: "https://fastly.jsdelivr.net/gh/ssrsub/ssr@master/Clash.yml"
  #   interval: 1800
  #   health-check:
  #     enable: true
  #     url: "https://www.google.com/generate_204"
  #     interval: 300

  # pmsub:
  #   type: http
  #   path: ./proxy/pmsub.yaml
  #   url: "https://sub.pmsub.me/clash.yaml"
  #   interval: 1800
  #   health-check:
  #     enable: true
  #     url: "https://www.google.com/generate_204"
  #     interval: 300

  # vveg26:
  #   type: http
  #   path: ./proxy/vveg26.yaml
  #   url: https://mareep.netlify.app/sub/merged_proxies_new.yaml
  #   interval: 1800

  chromego:
    type: http
    path: ./proxy/chromego.yaml
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/lgf4591/cloudflare-pages-vpn/main/ChromeGo_Merge/sub/merged_proxies_new.yaml
    interval: 1800

rules:
  # first RULE-SET PROXY
  - RULE-SET,ProxyMyDomain,PROXY
  # RULE-SET DIRECT
  - RULE-SET,DirectMyDomain,DIRECT
  # GETSITE
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,private,DIRECT
  - GEOSITE,youtube,PROXY
  - GEOSITE,google,PROXY
  - GEOSITE,twitter,PROXY
  - GEOSITE,pixiv,PROXY
  - GEOSITE,category-scholar-!cn,PROXY
  - GEOSITE,biliintl,PROXY
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOSITE,cn,DIRECT
  # GETIP
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  # MATCH
  - MATCH,PROXY

rule-providers:
  # 直连规则
  DirectMyDomain:
    behavior: domain
    interval: 86400
    path: ./rule-set/direct_domain.yaml
    type: http
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/FanchangWang/clash_config/main/direct_domain.yaml"
  # 代理规则
  ProxyMyDomain:
    behavior: domain
    interval: 86400
    path: ./rule-set/proxy_domain.yaml
    type: http
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/FanchangWang/clash_config/main/proxy_domain.yaml"
