mixed-port: 7890 # http(s) and SOCKS5
redir-port: 7892 # Redirect TCP and TProxy UDP

ipv6: true # 监听 ipv6，如果你网络不支持 ipv6 就别开

mode: rule # rule/global/direct/script

geodata-mode: true

log-level: info

allow-lan: true # 允许局域网其他机器使用代理
bind-address: "*" # 配合上面字段，允许全部局域网机器 ip

external-controller: 0.0.0.0:9090 # webui 监听 IP 端口
external-ui: ui/metacubexd # webui 相对目录
# external-ui: ui/yacd # webui 相对目录
# external-ui: ui/clash-dashboard # webui 相对目录

profile:
  store-selected: true # select proxy 缓存到 $HOME/.cache
  store-fake-ip: false # 设置 true 将允许 header XFF 转发你的真实 IP 给目标网站

tun:
  enable: true # 启动 tun 模式
  stack: system # system(系统模式) or gvisor(google 的一种沙盒模式)
  dns-hijack: # dns 劫持，需要 clash-premium
    - any:53
    - tcp://any:53
  auto-route: true # 全局路由，需要 clash-premium
  auto-redir: true # Linux nftable REDIRECT，需要 clash-premium
  auto-detect-interface: true # 自动选择出口网卡，需要 clash-premium

dns:
  enable: true # 启用 dns 处理
  prefer-h3: true # 启用 DOH http/3
  ipv6: true # 使用 ipv6 dns 解析，如果你网络不支持 ipv6 就别开
  listen: 0.0.0.0:1053 # 监听所有网络的 53 端口
  use-hosts: true # 允许使用 hosts 文件
  nameserver:
    - 180.76.76.76
    - 114.114.114.114
  fallback: # 回退 dns 服务器
    - tls://223.5.5.5:853
    - tls://8.8.4.4:853
  fallback-filter: # 回退规则
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - AUTO
      - Sall
    url: "https://www.google.com/generate_204"
    interval: 300

  - name: "AUTO"
    type: url-test
    use:
      - sub
      - anaer
      - ripaojiedian
      - ssrsub
      - pmsub
    url: "https://www.google.com/generate_204"
    interval: 300

  - name: "Sall"
    type: select
    use:
      - sub
      - anaer
      - ripaojiedian
      - ssrsub
      - pmsub
    url: "https://www.google.com/generate_204"
    interval: 300

proxy-providers:
  sub:
    type: http
    path: ./proxy/sub.yaml
    url: "https://renzheapi.com/sub?target=clash&new_name=true&url=https%3A%2F%2Fpastebin.com%2Fraw%2FGxR5pELe&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini"
    interval: 3600
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 300

  anaer:
    type: http
    path: ./proxy/anaer.yaml
    url: "https://raw.gitmirror.com/anaer/Sub/main/clash.yaml"
    interval: 3600
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 300

  ripaojiedian:
    type: http
    path: ./proxy/ripaojiedian.yaml
    url: "https://raw.gitmirror.com/ripaojiedian/freenode/main/clash"
    interval: 3600
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 300

  ssrsub:
    type: http
    path: ./proxy/ssrsub.yaml
    url: "https://raw.gitmirror.com/ssrsub/ssr/master/Clash.yml"
    interval: 3600
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 300

  pmsub:
    type: http
    path: ./proxy/pmsub.yaml
    url: "https://sub.pmsub.me/clash.yaml"
    interval: 3600
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 300

rules:
  # RULE-SET DIRECT
  - RULE-SET,DirectCnDomain,DIRECT
  # GETSITE
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,private,DIRECT
  - GEOSITE,youtube,PROXY
  - GEOSITE,google,PROXY
  - GEOSITE,twitter,PROXY
  - GEOSITE,pixiv,PROXY
  - GEOSITE,category-scholar-!cn,PROXY
  - GEOSITE,biliintl,PROXY
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOSITE,cn,DIRECT
  # RULE-SET PROXY
  - RULE-SET,ProxyDomain,PROXY
  # GETIP
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - DST-PORT,80/8080/443/8443,PROXY
  # MATCH
  - MATCH,DIRECT

rule-providers:
  # 直连规则
  DirectCnDomain:
    behavior: domain
    interval: 86400
    path: ./rule-set/cn_domain.yaml
    type: http
    url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/cn_domain.yaml"
  # 代理规则
  ProxyDomain:
    behavior: domain
    interval: 86400
    path: ./rule-set/proxy.yaml
    type: http
    url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/proxy.yaml"
