mixed-port: 7890 # http(s) and SOCKS5
redir-port: 7892 # Redirect TCP and TProxy UDP

ipv6: true # 监听 ipv6，如果你网络不支持 ipv6 就别开

mode: rule # rule/global/direct/script

#自定义 geodata url
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"

log-level: info

allow-lan: true # 允许局域网其他机器使用代理
bind-address: "*" # 配合上面字段，允许全部局域网机器 ip

external-controller: 0.0.0.0:9090 # webui 监听 IP 端口
external-ui: yacd # webui 静态页面存放相对目录 /root/.clash/clash/yacd
external-ui-name: yacd
# external-ui: clash-dashboard # webui 静态页面存放相对目录 /root/.clash/clash/clash-dashboard

profile:
  store-selected: true # select proxy 缓存到 $HOME/.cache
  store-fake-ip: false # 设置 true 将允许 header XFF 转发你的真实 IP 给目标网站

tun:
  enable: true # 启动 tun 模式
  stack: system # system(系统模式) or gvisor(google 的一种沙盒模式)
  dns-hijack: # dns 劫持，需要 clash-premium
    - any:53
    - tcp://any:53
  auto-route: true # 全局路由，需要 clash-premium
  auto-redir: true # Linux nftable REDIRECT，需要 clash-premium
  auto-detect-interface: true # 自动选择出口网卡，需要 clash-premium

dns:
  enable: true # 启用 dns 处理
  prefer-h3: true # 启用 DOH http/3
  ipv6: true # 使用 ipv6 dns 解析，如果你网络不支持 ipv6 就别开
  listen: 0.0.0.0:1053 # 监听所有网络的 53 端口
  # default-nameserver: # 默认的 dns 服务器，内置默认值就是下面这 2 个
  #   - 8.8.8.8 # 通常这 2 个是不需要更换的
  #   - 114.114.114.114 #如果你对这 2 个支持不好可以考虑换其他的
  #   - system # append DNS server from system configuration. If not found, it would print an error log and skip.
  use-hosts: true # 允许使用 hosts 文件
  nameserver:
    - "[2001:4860:4860::8888]:53"
    - "[2001:4860:4860::8844]:53"
    - https://doh.pub/dns-query
  fallback: # 回退 dns 服务器
    - https://dns.google/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
  fallback-filter: # 回退规则
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - DIRECT
      - REJECT
      - AUTO
      - Aanaer
      - Sall
    url: "https://www.google.com/generate_204"
    interval: 300

  - name: "AUTO"
    type: url-test
    use:
      - sub
      - anaer
      - ripaojiedian
      - ssrsub
      - pmsub
    url: "https://www.google.com/generate_204"
    interval: 300

  - name: "Aanaer"
    type: url-test
    use:
      - anaer
    url: "https://www.google.com/generate_204"
    interval: 300

  - name: "Sall"
    type: select
    use:
      - sub
      - anaer
      - ripaojiedian
      - ssrsub
      - pmsub
    url: "https://www.google.com/generate_204"
    interval: 300

proxy-providers:
  sub:
    type: http
    path: ./proxy/sub.yaml
    url: "https://renzheapi.com/sub?target=clash&new_name=true&url=https%3A%2F%2Fpastebin.com%2Fraw%2FGxR5pELe&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini"
    interval: 600
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 300

  anaer:
    type: http
    path: ./proxy/anaer.yaml
    url: "https://raw.gitmirror.com/anaer/Sub/main/clash.yaml"
    interval: 600
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 300

  ripaojiedian:
    type: http
    path: ./proxy/ripaojiedian.yaml
    url: "https://raw.gitmirror.com/ripaojiedian/freenode/main/clash"
    interval: 600
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 300

  ssrsub:
    type: http
    path: ./proxy/ssrsub.yaml
    url: "https://raw.gitmirror.com/ssrsub/ssr/master/Clash.yml"
    interval: 600
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 300

  pmsub:
    type: http
    path: ./proxy/pmsub.yaml
    url: "https://sub.pmsub.me/clash.yaml"
    interval: 600
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 300

rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,DirectLocalAreaNetwork,DIRECT
  - RULE-SET,DirectMicrosoft,DIRECT
  - RULE-SET,DirectApple,DIRECT
  - RULE-SET,DirectUnBan,DIRECT
  - RULE-SET,DirectGoogleCN,DIRECT
  - RULE-SET,DirectSteamCN,DIRECT
  - RULE-SET,DirectChinaDomain,DIRECT
  - RULE-SET,DirectChinaMedia,DIRECT
  - RULE-SET,RejectBanAD,REJECT
  - RULE-SET,RejectBanEasyList,REJECT
  - RULE-SET,RejectBanEasyListChina,REJECT
  - RULE-SET,RejectBanEasyPrivacy,REJECT
  - RULE-SET,RejectBanProgramAD,REJECT
  - RULE-SET,ProxyGoogleFCM,PROXY
  - RULE-SET,ProxyGFWlist,PROXY
  - RULE-SET,ProxyMedia,PROXY
  - GEOSITE,google,PROXY
  - GEOSITE,cn,DIRECT
  - RULE-SET,DirectChinaCompanyIp,DIRECT
  - RULE-SET,DirectChinaIp,DIRECT
  - RULE-SET,DirectChinaIpV6,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

rule-providers:
  # 直连规则
  DirectLocalAreaNetwork: # 本地网络
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml"
    interval: 86400
    path: ./ACL4SSR/LocalAreaNetwork.yaml
  DirectMicrosoft: # 微软
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml"
    interval: 86400
    path: ./ACL4SSR/Microsoft.yaml
  DirectApple: # 苹果
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml"
    interval: 86400
    path: ./ACL4SSR/Apple.yaml
  DirectUnBan: # 不应被广告规则拦截的域名
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml"
    interval: 86400
    path: ./ACL4SSR/UnBan.yaml
  DirectGoogleCN: # 谷歌 国内可直连域名
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCN.yaml"
    interval: 86400
    path: ./ACL4SSR/GoogleCN.yaml
  DirectSteamCN: # Stream 国内可直连域名
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/SteamCN.yaml"
    interval: 86400
    path: ./ACL4SSR/SteamCN.yaml
  DirectChinaDomain: # 国内网站域名
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml"
    interval: 86400
    path: ./ACL4SSR/ChinaDomain.yaml
  DirectChinaCompanyIp: # 中国云服务商ip端
    behavior: ipcidr
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml"
    interval: 86400
    path: ./ACL4SSR/ChinaCompanyIp.yaml
  DirectChinaIp: # 中国IP地址段ipv4
    behavior: ipcidr
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml"
    interval: 86400
    path: ./ACL4SSR/ChinaIp.yaml
  DirectChinaIpV6: # 中国IP地址段ipv6
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIpV6.yaml"
    interval: 86400
    path: ./ACL4SSR/ChinaIpV6.yaml
  DirectChinaMedia: # 中国媒体列表
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaMedia.yaml"
    interval: 86400
    path: ./ACL4SSR/ChinaMedia.yaml
  # 拒绝规则
  RejectBanAD: # 常见广告
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
    interval: 86400
    path: ./ACL4SSR/BanAD.yaml
  RejectBanEasyList: # 广告列表 adblock rules EasyList列表，只包含ABP中的 EasyList 内容
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml"
    interval: 86400
    path: ./ACL4SSR/BanEasyList.yaml
  RejectBanEasyListChina: # 广告列表 adblock rules EasyListChina列表，只包含ABP中的 EasyListChina 内容
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml"
    interval: 86400
    path: ./ACL4SSR/BanEasyListChina.yaml
  RejectBanEasyPrivacy: # 广告列表 adblock rules EasyPrivacy列表，隐私保护，屏蔽隐私追踪
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyPrivacy.yaml"
    interval: 86400
    path: ./ACL4SSR/BanEasyPrivacy.yaml
  RejectBanProgramAD: # 应用内广告
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml"
    interval: 86400
    path: ./ACL4SSR/BanProgramAD.yaml
  # 代理规则
  ProxyGoogleFCM: # 谷歌 FCM 推送
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml"
    interval: 86400
    path: ./ACL4SSR/GoogleFCM.yaml
  ProxyGFWlist: # GFW 拦截域名
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyGFWlist.yaml"
    interval: 86400
    path: ./ACL4SSR/ProxyGFWlist.yaml
  ProxyMedia: # 国外媒体
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml"
    interval: 86400
    path: ./ACL4SSR/ProxyMedia.yaml
