name: Daily Update

on:
  schedule:
    - cron: "10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 安装 uv
        uses: astral-sh/setup-uv@v4

      - name: 安装依赖
        run: uv sync

      - name: 执行脚本
        run: uv run python main.py

      - name: 提交修改
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet && echo "No changes" || (
            git commit -m "Auto update: $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" &&
            git push
          )
